# Generated by Django 5.1.1 on 2024-09-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_comment_blog_comment_comment_img_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_img',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
