# Generated by Django 5.1.1 on 2024-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usernames',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
