# Generated by Django 5.1.1 on 2024-09-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usernames',
        ),
    ]
